-- ESD System v0.1.0
-- 只建立 ESD 業務資料；平台帳號、密碼、部門、角色和菜單由 platform-system-server 管理。
CREATE DATABASE IF NOT EXISTS platform_esd
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE platform_esd;

CREATE TABLE IF NOT EXISTS esd_person_profile (
  id BIGINT NOT NULL,
  site_code VARCHAR(32) NOT NULL,
  platform_user_id BIGINT NOT NULL,
  employee_no VARCHAR(64) NOT NULL,
  employee_name VARCHAR(100) NOT NULL,
  dept_id BIGINT NULL,
  dept_name VARCHAR(100) NULL,
  supervisor_user_id BIGINT NULL,
  supervisor_name VARCHAR(100) NULL,
  floor_code VARCHAR(32) NULL,
  shift_code VARCHAR(32) NULL,
  esd_status TINYINT NOT NULL DEFAULT 1 COMMENT '1 ENABLED, 0 DISABLED',
  creator VARCHAR(64) NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater VARCHAR(64) NULL,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted BIT NOT NULL DEFAULT b'0',
  active_bind_key VARCHAR(120) GENERATED ALWAYS AS
    (CASE WHEN deleted = b'0' THEN CONCAT(site_code, ':', platform_user_id) ELSE NULL END) STORED,
  PRIMARY KEY (id),
  UNIQUE KEY uk_person_site_user (active_bind_key),
  KEY idx_person_employee (site_code, employee_no),
  KEY idx_person_dept (site_code, dept_id),
  CONSTRAINT ck_person_status CHECK (esd_status IN (0, 1))
) ENGINE=InnoDB COMMENT='ESD 人員擴展檔';

CREATE TABLE IF NOT EXISTS esd_asset (
  id BIGINT NOT NULL,
  asset_code VARCHAR(64) NOT NULL,
  site_code VARCHAR(32) NOT NULL,
  asset_type TINYINT NOT NULL COMMENT '1 GARMENT, 2 SHOES',
  color_code VARCHAR(32) NOT NULL,
  size_code VARCHAR(32) NOT NULL,
  lifecycle_status TINYINT NOT NULL COMMENT '10 AVAILABLE, 20 ISSUED, 30 IN_LAUNDRY, 40 RETIRED, 50 LOST',
  current_holder_user_id BIGINT NULL,
  current_holder_no VARCHAR(64) NULL,
  current_holder_name VARCHAR(100) NULL,
  clean_count INT NOT NULL DEFAULT 0,
  version INT NOT NULL DEFAULT 0,
  creator VARCHAR(64) NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater VARCHAR(64) NULL,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted BIT NOT NULL DEFAULT b'0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_asset_code (asset_code),
  KEY idx_asset_site_status (site_code, lifecycle_status),
  KEY idx_asset_holder (site_code, current_holder_user_id, asset_type, lifecycle_status),
  CONSTRAINT ck_asset_type CHECK (asset_type IN (1, 2)),
  CONSTRAINT ck_asset_status CHECK (lifecycle_status IN (10, 20, 30, 40, 50)),
  CONSTRAINT ck_asset_clean_count CHECK (clean_count >= 0),
  CONSTRAINT ck_asset_holder CHECK ((lifecycle_status = 20 AND current_holder_user_id IS NOT NULL) OR (lifecycle_status <> 20 AND current_holder_user_id IS NULL))
) ENGINE=InnoDB COMMENT='ESD 資產主檔';

CREATE TABLE IF NOT EXISTS esd_issue_record (
  id BIGINT NOT NULL,
  request_id VARCHAR(64) NOT NULL,
  site_code VARCHAR(32) NOT NULL,
  asset_id BIGINT NOT NULL,
  asset_code VARCHAR(64) NOT NULL,
  asset_type TINYINT NOT NULL,
  employee_user_id BIGINT NOT NULL,
  employee_no VARCHAR(64) NOT NULL,
  employee_name VARCHAR(100) NOT NULL,
  issue_operator_user_id BIGINT NOT NULL,
  issue_operator_name VARCHAR(100) NULL,
  issue_date DATE NOT NULL,
  record_status TINYINT NOT NULL DEFAULT 1 COMMENT '1 ACTIVE, 2 COMPLETED, 3 TERMINATED, 4 REVERSED',
  close_time DATETIME NULL,
  creator VARCHAR(64) NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater VARCHAR(64) NULL,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted BIT NOT NULL DEFAULT b'0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_issue_request (request_id),
  KEY idx_issue_employee (site_code, employee_user_id, asset_type, record_status),
  KEY idx_issue_asset (site_code, asset_id, record_status)
) ENGINE=InnoDB COMMENT='ESD 發放記錄';

CREATE TABLE IF NOT EXISTS esd_return_record (
  id BIGINT NOT NULL,
  request_id VARCHAR(64) NOT NULL,
  site_code VARCHAR(32) NOT NULL,
  asset_id BIGINT NOT NULL,
  asset_code VARCHAR(64) NOT NULL,
  issue_record_id BIGINT NOT NULL,
  employee_user_id BIGINT NOT NULL,
  employee_no VARCHAR(64) NOT NULL,
  employee_name VARCHAR(100) NOT NULL,
  return_condition TINYINT NOT NULL COMMENT '1 NORMAL, 2 DAMAGED, 3 SOILED',
  disposition TINYINT NOT NULL COMMENT '1 RESTOCK, 2 LAUNDER',
  returner_user_id BIGINT NULL,
  returner_name VARCHAR(100) NULL,
  receiver_user_id BIGINT NOT NULL,
  receiver_name VARCHAR(100) NULL,
  return_date DATE NOT NULL,
  record_status TINYINT NOT NULL DEFAULT 2,
  creator VARCHAR(64) NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater VARCHAR(64) NULL,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted BIT NOT NULL DEFAULT b'0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_return_request (request_id),
  KEY idx_return_asset (site_code, asset_id, return_date),
  KEY idx_return_employee (site_code, employee_user_id, return_date)
) ENGINE=InnoDB COMMENT='ESD 回收記錄';

CREATE TABLE IF NOT EXISTS esd_laundry_record (
  id BIGINT NOT NULL,
  request_id VARCHAR(64) NOT NULL,
  site_code VARCHAR(32) NOT NULL,
  asset_id BIGINT NOT NULL,
  asset_code VARCHAR(64) NOT NULL,
  return_record_id BIGINT NOT NULL,
  send_operator_user_id BIGINT NOT NULL,
  send_operator_name VARCHAR(100) NULL,
  send_time DATETIME NOT NULL,
  complete_operator_user_id BIGINT NULL,
  complete_operator_name VARCHAR(100) NULL,
  complete_time DATETIME NULL,
  record_status TINYINT NOT NULL DEFAULT 1 COMMENT '1 ACTIVE, 2 COMPLETED, 3 TERMINATED, 4 REVERSED',
  creator VARCHAR(64) NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater VARCHAR(64) NULL,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted BIT NOT NULL DEFAULT b'0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_laundry_request (request_id),
  KEY idx_laundry_active (site_code, asset_id, record_status),
  KEY idx_laundry_history (site_code, complete_time)
) ENGINE=InnoDB COMMENT='ESD 清洗記錄';

CREATE TABLE IF NOT EXISTS esd_scrap_record (
  id BIGINT NOT NULL,
  request_id VARCHAR(64) NOT NULL,
  site_code VARCHAR(32) NOT NULL,
  asset_id BIGINT NOT NULL,
  asset_code VARCHAR(64) NOT NULL,
  reason_code VARCHAR(32) NOT NULL,
  previous_status TINYINT NOT NULL,
  previous_holder_user_id BIGINT NULL,
  previous_active_issue_id BIGINT NULL,
  previous_active_laundry_id BIGINT NULL,
  previous_clean_count INT NOT NULL,
  asset_version_before INT NOT NULL,
  scrap_date DATE NOT NULL,
  record_status TINYINT NOT NULL DEFAULT 2 COMMENT '2 COMPLETED, 4 REVERSED',
  reverse_operator_user_id BIGINT NULL,
  reverse_time DATETIME NULL,
  creator VARCHAR(64) NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater VARCHAR(64) NULL,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted BIT NOT NULL DEFAULT b'0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_scrap_request (request_id),
  KEY idx_scrap_asset (site_code, asset_id, scrap_date)
) ENGINE=InnoDB COMMENT='ESD 報廢記錄';

CREATE TABLE IF NOT EXISTS esd_loss_record (
  id BIGINT NOT NULL,
  request_id VARCHAR(64) NOT NULL,
  site_code VARCHAR(32) NOT NULL,
  asset_id BIGINT NOT NULL,
  asset_code VARCHAR(64) NOT NULL,
  responsible_employee_user_id BIGINT NULL,
  responsible_employee_no VARCHAR(64) NULL,
  responsible_employee_name VARCHAR(100) NULL,
  handle_method VARCHAR(32) NOT NULL,
  previous_status TINYINT NOT NULL,
  previous_holder_user_id BIGINT NULL,
  previous_active_issue_id BIGINT NULL,
  previous_active_laundry_id BIGINT NULL,
  previous_clean_count INT NOT NULL,
  asset_version_before INT NOT NULL,
  discover_date DATE NOT NULL,
  record_status TINYINT NOT NULL DEFAULT 2 COMMENT '2 COMPLETED, 4 REVERSED',
  reverse_operator_user_id BIGINT NULL,
  reverse_time DATETIME NULL,
  creator VARCHAR(64) NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater VARCHAR(64) NULL,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted BIT NOT NULL DEFAULT b'0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_loss_request (request_id),
  KEY idx_loss_asset (site_code, asset_id, discover_date)
) ENGINE=InnoDB COMMENT='ESD 遺失記錄';

CREATE TABLE IF NOT EXISTS esd_alert (
  id BIGINT NOT NULL,
  site_code VARCHAR(32) NOT NULL,
  employee_user_id BIGINT NOT NULL,
  employee_no VARCHAR(64) NOT NULL,
  employee_name VARCHAR(100) NOT NULL,
  alert_type TINYINT NOT NULL COMMENT '1 MULTIPLE_GARMENTS, 2 MULTIPLE_SHOES',
  hold_count INT NOT NULL,
  status TINYINT NOT NULL DEFAULT 1 COMMENT '1 ACTIVE, 2 RESOLVED',
  first_trigger_time DATETIME NOT NULL,
  last_trigger_time DATETIME NOT NULL,
  resolved_time DATETIME NULL,
  description VARCHAR(500) NULL,
  creator VARCHAR(64) NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updater VARCHAR(64) NULL,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted BIT NOT NULL DEFAULT b'0',
  PRIMARY KEY (id),
  UNIQUE KEY uk_alert_employee_type (site_code, employee_user_id, alert_type),
  KEY idx_alert_status (site_code, status, last_trigger_time)
) ENGINE=InnoDB COMMENT='ESD 一人多持報警';

CREATE TABLE IF NOT EXISTS esd_asset_event (
  id BIGINT NOT NULL,
  site_code VARCHAR(32) NOT NULL,
  asset_id BIGINT NOT NULL,
  asset_code VARCHAR(64) NOT NULL,
  event_type VARCHAR(32) NOT NULL,
  before_status TINYINT NULL,
  after_status TINYINT NOT NULL,
  business_record_id BIGINT NULL,
  operator_user_id BIGINT NOT NULL,
  operator_name VARCHAR(100) NULL,
  request_id VARCHAR(64) NULL,
  payload_json JSON NULL,
  event_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_event_asset (site_code, asset_id, event_time),
  KEY idx_event_request (request_id)
) ENGINE=InnoDB COMMENT='ESD 資產不可變事件帳';

CREATE TABLE IF NOT EXISTS esd_import_batch (
  id BIGINT NOT NULL,
  request_id VARCHAR(64) NOT NULL,
  site_code VARCHAR(32) NOT NULL,
  module_code VARCHAR(32) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  file_sha256 CHAR(64) NOT NULL,
  total_rows INT NOT NULL,
  error_rows INT NOT NULL DEFAULT 0,
  batch_status TINYINT NOT NULL COMMENT '1 VALIDATING, 2 SUCCESS, 3 FAILED',
  error_summary JSON NULL,
  operator_user_id BIGINT NOT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_import_request (request_id),
  KEY idx_import_site_time (site_code, create_time)
) ENGINE=InnoDB COMMENT='ESD 導入批次審計';

CREATE TABLE IF NOT EXISTS esd_backup_record (
  id BIGINT NOT NULL,
  site_code VARCHAR(32) NULL,
  operation_type TINYINT NOT NULL COMMENT '1 EXPORT, 2 RESTORE, 3 PRE_RESTORE, 4 CLEAR',
  schema_version VARCHAR(32) NOT NULL,
  application_version VARCHAR(32) NOT NULL,
  file_name VARCHAR(255) NULL,
  file_sha256 CHAR(64) NULL,
  storage_key VARCHAR(500) NULL,
  record_count INT NULL,
  operation_status TINYINT NOT NULL COMMENT '1 STARTED, 2 SUCCESS, 3 FAILED',
  operator_user_id BIGINT NOT NULL,
  error_message VARCHAR(1000) NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_backup_site_time (site_code, create_time)
) ENGINE=InnoDB COMMENT='ESD 備份恢復審計';
