spring:
  cloud:
    nacos:
      discovery:
        enabled: ${NACOS_DISCOVERY_ENABLED:false}
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      config:
        enabled: false

esd:
  local-debug-auth-enabled: ${ESD_LOCAL_DEBUG_AUTH_ENABLED:false}
